name: app_filmes
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.6.0
  get: 4.3.8
  flutter:
    sdk: flutter
  firebase_auth: ^3.1.1
  firebase_remote_config: ^0.11.0
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.1.0
  fluttericon: ^2.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AppFilmesIcons
      fonts:
        - asset: assets/fonts/AppFilmesIcons.ttf

    - family: Metropolis
      fonts:
        - asset: assets/fonts/metropolis/Metropolis-Regular.otf
        - asset: assets/fonts/metropolis/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/metropolis/Metropolis-Bold.otf

get_cli:
  sub_folder: false
