name: app_filmes
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.6.0
  get: 4.3.8
  flutter:
    sdk: flutter
  firebase_auth: ^3.1.1
  firebase_remote_config: ^0.11.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
