/// Flutter icons AppFilmesIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppFilmesIcons
///      fonts:
///       - asset: fonts/AppFilmesIcons.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class AppFilmesIcons {
  AppFilmesIcons._();

  static const _kFontFam = 'AppFilmesIcons';

  static const IconData heart = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData heart_empty = IconData(0xe803, fontFamily: _kFontFam);
}
